// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBHYGGBh-6qoOYgNMeBoORLwUAHE1s7c',
    appId: '1:775835803985:web:44d7b8cfb9646f9c00f370',
    messagingSenderId: '775835803985',
    projectId: 'financial-tracker-e61d2',
    authDomain: 'financial-tracker-e61d2.firebaseapp.com',
    storageBucket: 'financial-tracker-e61d2.firebasestorage.app',
    measurementId: 'G-XTHV2WGN5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjx2E6bW32addmZ_0Hu-Yd1VQEJ3rldU',
    appId: '1:775835803985:android:4059ab11bace53c100f370',
    messagingSenderId: '775835803985',
    projectId: 'financial-tracker-e61d2',
    storageBucket: 'financial-tracker-e61d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZR1jUeZxaeDsvdcPH5_HjUrlTUsZ34e4',
    appId: '1:775835803985:ios:36d69af46e30e9ee00f370',
    messagingSenderId: '775835803985',
    projectId: 'financial-tracker-e61d2',
    storageBucket: 'financial-tracker-e61d2.firebasestorage.app',
    iosBundleId: 'com.example.financialTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZR1jUeZxaeDsvdcPH5_HjUrlTUsZ34e4',
    appId: '1:775835803985:ios:36d69af46e30e9ee00f370',
    messagingSenderId: '775835803985',
    projectId: 'financial-tracker-e61d2',
    storageBucket: 'financial-tracker-e61d2.firebasestorage.app',
    iosBundleId: 'com.example.financialTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdBHYGGBh-6qoOYgNMeBoORLwUAHE1s7c',
    appId: '1:775835803985:web:d87b71135776ff1a00f370',
    messagingSenderId: '775835803985',
    projectId: 'financial-tracker-e61d2',
    authDomain: 'financial-tracker-e61d2.firebaseapp.com',
    storageBucket: 'financial-tracker-e61d2.firebasestorage.app',
    measurementId: 'G-DSHP6NLH8R',
  );
}
